server:
  port: 17071
  error:
    whitelabel:
      enabled: false
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#  profiles:
#    active: local,oracle,C0001 
    
endpoints:
  jmx:
    domain: enio-agent
    unique-names: true
    
enio:
  welcome:
    message: Welcome Enio Agent!
  api:
    version: v1
    context-path: /api
    uri-path:
      item: /items
      dept: /depts
      user: /users
      pr: /pr


multipart:
  max-file-size: 30MB
  max-request-size: 300MB