---
#덕성여자대학교
spring:
  profiles: oracle,D0001

# 덕성 운영 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@203.252.210.55:1526:ORA12DSU    
    username: ebid
    password: ebid#2158
  devtools:
    restart:
      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: /app/ebid/enio/enio-agent/logs/               #덕성개발

enio:
  univ-cd: D0001
  file:
    temp-dir: /app/ebid/enio/enio-agent/temps/      #덕성개발
    pds-dir: /app/ebid/enio/enio-agent/pds/            #덕성개발
  scheduled:
    cron: 0 0/1 * * * ?

---
#울산대학교
spring:
  profiles: mssql,A01BU
 
 # 울산대학교 개발,운영 ##       
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://1.253.80.140:1433/enio
    username: enio
    password: enio_0101!
  devtools:
    restart:
      enabled: true    
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/mssql/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: d:/enio/enio-agent/logs/  

enio:
  univ-cd: A01BU
  file:
    temp-dir: d:/enio/enio-agent/temps/
    pds-dir: d:/enio/enio-agent/pds/
  scheduled:  
    cron: 0 0/1 * * * ?

---
#(주)이노가드
spring:
  profiles: mssql,S0001
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://dev-app.ebiz4u.co.kr:1433/enioagent
    username: enioagent
    password: eniojjang
  devtools:
    restart:
      enabled: true    
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/mssql/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: D:/enio/enio-agent/logs/

enio:
  univ-cd: S0001
  file:
    temp-dir: D:/enio/enio-agent/temps/
    pds-dir: D:/enio/enio-agent/pds/
  scheduled:
    cron: 0 0/1 * * * ?

---
#호서대학교
spring:
  profiles: oracle,S0020

# 호서 운영 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@203.252.210.55:1526:ORA12DSU    
    username: ebid
    password: ebid#2158
  devtools:
    restart:
      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: /app/ebid/enio/enio-agent/logs/               #호서 개발

enio:
  univ-cd: S0020
  file:
    temp-dir: /app/ebid/enio/enio-agent/temps/      #호서 개발
    pds-dir: /app/ebid/enio/enio-agent/pds/            #호서 개발
  scheduled:
    cron: 0 0/1 * * * ?

---
#성신여자대학교
spring:
  profiles: oracle,S0037
            
# 성신여대 운영 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@//172.16.25.205:1521/TIS
    username: ebid_ap
    password: ebid_ap1129!
  devtools:
    restart:
      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: /apps/ebid/enio/enio-agent/logs/               #성신여대 운영

enio:
  univ-cd: S0037
  file:
    temp-dir: /apps/ebid/enio/enio-agent/temps/      #성신여대 운영
    pds-dir: /apps/ebid/enio/enio-agent/pds/            #성신여대 운영

  scheduled:
    cron: 0 0/1 * * * ?

---
#상명대학교
spring:
  profiles: DB2,S0014
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:db2://172.18.0.106:40000/SMUDBIS
    username: EBIZ
    password: ebiz1027!@
  devtools:
    restart:
      enabled: true    
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/db2/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: c:/enio/enio-agent/logs/

enio:
  univ-cd: S0014
  file:
    temp-dir: c:/enio/enio-agent/temps/
    pds-dir: c:/enio/enio-agent/pds/
    
  scheduled:
    cron: 0 0/1 * * * ?

---
#중앙대학교
spring:
  profiles: oracle,C0001

# 중앙대학교 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@10.77.3.2:1521/CAUDB
    username: inogard
    password: ino2019!22
  devtools:
    restart:
      enabled: true
            
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: c:/enio/enio-agent/logs/

enio:
  univ-cd: C0001
  file:
    temp-dir: c:/enio/enio-agent/temps/
    pds-dir: c:/enio/enio-agent/pds/

  scheduled:
    cron: 0 0/1 * * * ?

---
#한양사이버대학교
spring:
  profiles: oracle,A013Q

# 한양사이버대학교 운영 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@10.100.192.54:1521/HYCDB
    username: enio
    password: enio01
  devtools:
    restart:
      enabled: true
            
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: d:/enio/enio-agent/logs/

enio:
  univ-cd: A013Q
  file:
    temp-dir: d:/enio/enio-agent/temps/
    pds-dir: d:/enio/enio-agent/pds/
    
  scheduled:
    cron: 0 0/1 * * * ?