---
#덕성여자대학교
spring:
  profiles: oracle,D0001

# 이노가드 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.212:1521:orcl
    username: enio
    password: enio
  devtools:
    restart:
      enabled: true
            
# 덕성 개발 ##
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@203.252.210.55:1526:DEV12DSU
#    username: ebid
#    password: ebid
#  devtools:
#    restart:
#      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
#  path: /app/ebid/enio/enio-agent/logs/               #덕성개발
  path: /home/agttest/enio/enio-agent/D0001/logs/               #이노가드 ERP 덕성개발
#  path: E:/Develop/var/enio/enio-agent/D0001/logs/  

enio:
  univ-cd: D0001
  file:
#    temp-dir: /app/ebid/enio/enio-agent/temps/      #덕성개발
#    pds-dir: /app/ebid/enio/enio-agent/pds/            #덕성개발
    temp-dir: /home/agttest/enio/enio-agent/D0001/temps/      #이노가드 ERP 덕성개발
    pds-dir: /home/agttest/enio/enio-agent/D0001/pds/            #이노가드 ERP 덕성개발
#    temp-dir: E:/Develop/var/enio/enio-agent/D0001/temps/
#    pds-dir: E:/Develop/var/enio/enio-agent/D0001/pds/
  scheduled:
    cron: 0 0/1 * * * ?

---
#울산대학교
spring:
  profiles: mssql,A01BU
 
 # 이노가드 개발 ## 
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://dev-app.ebiz4u.co.kr:1433/enioagent
    username: enioagent
    password: eniojjang
  devtools:
    restart:
      enabled: true

 # 울산대학교 개발 ##       
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:jtds:sqlserver://172.25.80.140:1433/enio
#    username: enio
#    password: enio_0101!
#  devtools:
#    restart:
#      enabled: true
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/mssql/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
#  path: d:/enio/enio-agent/logs/
  path: e:/enio/enio-agent/A01BU/logs/

enio:
  univ-cd: A01BU
  file:
#    temp-dir: d:/enio/enio-agent/temps/
#    pds-dir: d:/enio/enio-agent/pds/
    temp-dir: e:/enio/enio-agent/A01BU/temps/
    pds-dir: e:/enio/enio-agent/A01BU/pds/
  scheduled:
    cron: 0 0/1 * * * ?

---
#(주)이노가드
spring:
  profiles: mssql,S0001
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:jtds:sqlserver://dev-app.ebiz4u.co.kr:1433/enioagent
    username: enioagent
    password: eniojjang
  devtools:
    restart:
      enabled: true    
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/mssql/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: E:/Develop/var/enio/enio-agent/S0001/logs/

enio:
  univ-cd: S0001
  file:
    temp-dir: E:/Develop/var/enio/enio-agent/S0001/temps/
    pds-dir: E:/Develop/var/enio/enio-agent/S0001/pds/

  scheduled:
    cron: 0 0/1 * * * ?   

---
#호서대학교
spring:
  profiles: oracle,S0020

# 이노가드 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@210.121.194.253:1521:orcl
    username: enio
    password: enio
  devtools:
    restart:
      enabled: true
            
# 호서대 개발 ##
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@203.252.210.55:1526:DEV12DSU
#    username: ebid
#    password: ebid
#  devtools:
#    restart:
#      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
#  path: d:/enio/enio-agent/logs/
  path: e:/enio/enio-agent/S0020/logs/

enio:
  univ-cd: S0020
  file:
#    temp-dir: d:/enio/enio-agent/temps/
#    pds-dir: d:/enio/enio-agent/pds/
    temp-dir: e:/enio/enio-agent/S0020/temps/
    pds-dir: e:/enio/enio-agent/S0020/pds/
  scheduled:
    cron: 0 0/1 * * * ?

---
#성신여자대학교
spring:
  profiles: oracle,S0037

# 이노가드 개발 ##
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@210.121.194.253:1521:orcl
#    username: enio
#    password: enio
#  devtools:
#    restart:
#      enabled: true
            
# 성신여대 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@172.16.25.73:1521:TISD
    username: EBID_AP
    password: ebid1129
  devtools:
    restart:
      enabled: true    

mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: /apps/ebid/enio/enio-agent/logs/               #성신여대 개발
#  path: /home/agttest/enio/enio-agent/S0037/logs/               #이노가드 ERP서버 개발
#  path: E:/Develop/var/enio/enio-agent/S0037/logs/  

enio:
  univ-cd: S0037
  file:
    temp-dir: /apps/ebid/enio/enio-agent/temps/      #성신여대 개발
    pds-dir: /apps/ebid/enio/enio-agent/pds/            #성신여대개발
#    temp-dir: /home/agttest/enio/enio-agent/S0037/temps/      #이노가드 ERP 개발
#    pds-dir: /home/agttest/enio/enio-agent/S0037/pds/            #이노가드 ERP 개발
#    temp-dir: E:/Develop/var/enio/enio-agent/S0037/temps/
#    pds-dir: E:/Develop/var/enio/enio-agent/S0037/pds/
  scheduled:
    cron: 0 0/1 * * * ?

---
#상명대학교
spring:
  profiles: DB2,S0014
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:db2://203.237.175.17:40000/SMUDEV
    username: ebiz
    password: ebiz
  devtools:
    restart:
      enabled: true    
      
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/db2/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
#  path: d:/enio/enio-agent/S0014/logs/      #이노가드 개발
  path: c:/enio/enio-agent/logs/

enio:
  univ-cd: S0014
  file:
#    temp-dir: d:/enio/enio-agent/S0014/temps/          #이노가드 개발
#    pds-dir: d:/enio/enio-agent/S0014/pds/               #이노가드 개발
    temp-dir: c:/enio/enio-agent/temps/
    pds-dir: c:/enio/enio-agent/pds/
    
  scheduled:
    cron: 0 0/1 * * * ?

---
#중앙대학교
spring:
  profiles: oracle,C0001

# 이노가드 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@112.220.235.235:1521:orcl
    username: enio
    password: enio
  devtools:
    restart:
      enabled: true
            
# 중앙대학교 개발 ##
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@192.168.0.212:1521:orcl
#    username: enio
#    password: enio
#  devtools:
#    restart:
#      enabled: true
            
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
  path: e:/enio/enio-agent/C0001/logs/      #이노가드 개발
#  path: c:/enio/enio-agent/logs/

enio:
  univ-cd: C0001
  file:
    temp-dir: e:/enio/enio-agent/C0001/temps/          #이노가드 개발
    pds-dir: e:/enio/enio-agent/C0001/pds/               #이노가드 개발
#    temp-dir: c:/enio/enio-agent/temps/
#    pds-dir: c:/enio/enio-agent/pds/
    
  scheduled:
    cron: 0 0/1 * * * ?

---
#한양사이버대학교
spring:
  profiles: oracle,A013Q

# 이노가드 개발 ##
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:oracle:thin:@112.220.235.235:1521:orcl
#    username: enio
#    password: enio
#  devtools:
#    restart:
#      enabled: true
            
# 한양사이버대학교 개발 ##
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@10.200.190.52:1521:HYCDBDEV
    username: enio
    password: enio01
  devtools:
    restart:
      enabled: true
            
mybatis:
  typeAliasesPackage: kr.co.inogard.enio.agent.domain
  mapperLocations: classpath:/mappers/oracle/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true
    jdbcTypeForNull: varchar

logging:
#  path: e:/enio/enio-agent/A013Q/logs/      #이노가드 개발
  path: d:/enio/enio-agent/logs/

enio:
  univ-cd: A013Q
  file:
#    temp-dir: e:/enio/enio-agent/A013Q/temps/          #이노가드 개발
#    pds-dir: e:/enio/enio-agent/A013Q/pds/               #이노가드 개발
    temp-dir: d:/enio/enio-agent/temps/
    pds-dir: d:/enio/enio-agent/pds/
    
  scheduled:
    cron: 0 0/1 * * * ?